test_that("pandoc_available() works", {
  skip_on_cran()
  skip_if_offline()
  suppressMessages(pandoc_install("2.11.4"))
  old <- suppressMessages(pandoc_set_version("2.11.4", FALSE))
  expect_true(pandoc_available())
  expect_true(pandoc_available(min = "2.7.3"))
  expect_false(pandoc_available(max = "2.7.3"))
  expect_true(pandoc_available(min = "2.7.3", max = "2.14.1"))
  expect_false(pandoc_available(min = "2.7.3", max = "2.10.1"))
  expect_false(pandoc_available(max = "2.11.4", strict = TRUE))
  expect_false(pandoc_available(min = "2.11.4", strict = TRUE))
  # as if no active version
  pandoc_active_set("")
  expect_false(pandoc_available())
  suppressMessages(pandoc_set_version(old, rmarkdown = FALSE))
})
