# NOTE: This workflow is overkill for most R packages
# check-standard.yaml is likely a better choice
# usethis::use_github_action("check-standard") will install it.
#
# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
    path-ignore:
      - .github/workflows/pkgdown.yaml
  pull_request:
    branches:
      - main
      - master
    path-ignore:
    - .github/workflows/pkgdown.yaml
  workflow_dispatch:

name: R-CMD-check

jobs:
  matrix:
    name: Build matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2

      - name: Build matrix conditionnaly
        id: set-matrix
        run: |
          # Only run on windows unless triggered manually
          # https://www.cynkra.com/blog/2020-12-23-dynamic-gha/
          windowsonly=${{ github.event_name != 'workflow_dispatch' }}

          matrix=$((
            echo '{ "config" : ['
            echo '{"os": "windows-latest","r": "release"}'
            if [ $windowsonly == 'false' ]; then
              echo ','
              echo '{"os": "macOS-latest","r": "release"},'
              echo '{"os": "ubuntu-18.04","r": "release"}'
            fi
            echo ']}'
          ) | jq -c .)
          echo $matrix
          echo $matrix | jq .
          echo "::set-output name=matrix::$matrix"

  check-matrix:
    runs-on: ubuntu-latest
    name: Check Matrix
    needs: matrix
    steps:
      - name: Install json2yaml
        run: |
          sudo npm install -g json2yaml

      - name: Check matrix definition
        run: |
          matrix='${{ needs.matrix.outputs.matrix }}'
          echo $matrix
          echo $matrix | jq .
          echo $matrix | json2yaml


  R-CMD-check:
    needs: matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.matrix.outputs.matrix)}}

    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
